// Auto-generated by sync-ios-icons.js
// Do not edit manually
// Generated: 2025-12-18T19:30:50.808Z

import SwiftUI

// MARK: - DSIcon

/// Design System icons from Figma
/// Usage: Image(dsIcon: .add) or DSIcon.add.image
public enum DSIcon: String, CaseIterable, Sendable {
    case threeSixtySpin = "ic_360spin"
    case add = "ic_add"
    case apron = "ic_apron"
    case ar = "ic_ar"
    case arrowBack = "ic_arrow_back"
    case arrowDown = "ic_arrow_down"
    case arrowForward = "ic_arrow_forward"
    case arrowUp = "ic_arrow_up"
    case assemble = "ic_assemble"
    case authorizeCard = "ic_authorize_card"
    case badge = "ic_badge"
    case barcode = "ic_barcode"
    case bathtubs = "ic_bathtubs"
    case bell = "ic_bell"
    case betaAddCart = "ic_beta_add_cart"
    case betaAddToList = "ic_beta_add_to_list"
    case betaLocationIcon = "ic_beta_location_icon"
    case betaMagicApron = "ic_beta_magic_apron"
    case betaNumberCart = "ic_beta_number_cart"
    case betaOrderSample = "ic_beta_order_sample"
    case betaPlaceholder = "ic_beta_placeholder"
    case betaQuickView = "ic_beta_quick_view"
    case betaSparkle = "ic_beta_sparkle"
    case blinds = "ic_blinds"
    case bookmarkFilled = "ic_bookmark_filled"
    case bookmarkOutline = "ic_bookmark_outline"
    case box = "ic_box"
    case boxTruck = "ic_box_truck"
    case bucket = "ic_bucket"
    case buyAgain = "ic_buy_again"
    case buyingGuide = "ic_buying_guide"
    case cabinet = "ic_cabinet"
    case calculator = "ic_calculator"
    case calendar = "ic_calendar"
    case camera = "ic_camera"
    case cancel = "ic_cancel"
    case car = "ic_car"
    case cardCvv = "ic_card_cvv"
    case cardNumber = "ic_card_number"
    case carpetInstall = "ic_carpet_install"
    case cart = "ic_cart"
    case catalog = "ic_catalog"
    case ceilingFan = "ic_ceiling_fan"
    case certificate = "ic_certificate"
    case chat = "ic_chat"
    case checkmark = "ic_checkmark"
    case clock = "ic_clock"
    case close = "ic_close"
    case compare = "ic_compare"
    case cookingWares = "ic_cooking_wares"
    case counterTop = "ic_counter_top"
    case creditCard = "ic_credit_card"
    case curbside = "ic_curbside"
    case curtain = "ic_curtain"
    case customOptions = "ic_custom_options"
    case danger = "ic_danger"
    case dangerOutline = "ic_danger_outline"
    case delivery = "ic_delivery"
    case deliveryexpress = "ic_deliveryexpress"
    case deliveryunavailable = "ic_deliveryunavailable"
    case dishwasher = "ic_dishwasher"
    case document = "ic_document"
    case door = "ic_door"
    case downArrowleft = "ic_down_arrowleft"
    case downArrowright = "ic_down_arrowright"
    case download = "ic_download"
    case drill = "ic_drill"
    case duplicate = "ic_duplicate"
    case edit = "ic_edit"
    case electrical = "ic_electrical"
    case email = "ic_email"
    case faucets = "ic_faucets"
    case fence = "ic_fence"
    case filters = "ic_filters"
    case financialServices = "ic_financial_services"
    case flag = "ic_flag"
    case floor = "ic_floor"
    case garage = "ic_garage"
    case gas = "ic_gas"
    case generator = "ic_generator"
    case giftCard = "ic_gift_card"
    case graduationCap = "ic_graduation_cap"
    case gridview = "ic_gridview"
    case grill = "ic_grill"
    case hammer = "ic_hammer"
    case heartFilled = "ic_heart_filled"
    case heartOutline = "ic_heart_outline"
    case hide = "ic_hide"
    case home = "ic_home"
    case howTo = "ic_how_to"
    case image = "ic_image"
    case independentLiving = "ic_independent_living"
    case info = "ic_info"
    case infoOutline = "ic_info_outline"
    case instantCheckout = "ic_instant_checkout"
    case instorePickup = "ic_instore_pickup"
    case key = "ic_key"
    case largeEquipment = "ic_large_equipment"
    case lawnGarden = "ic_lawn_garden"
    case lightBulb = "ic_light_bulb"
    case lighting = "ic_lighting"
    case listView = "ic_list_view"
    case location = "ic_location"
    case locked = "ic_locked"
    case locker = "ic_locker"
    case mailbox = "ic_mailbox"
    case measure = "ic_measure"
    case medal = "ic_medal"
    case menu = "ic_menu"
    case mic = "ic_mic"
    case mobile = "ic_mobile"
    case more = "ic_more"
    case move = "ic_move"
    case note = "ic_note"
    case online = "ic_online"
    case orderTracking = "ic_order_tracking"
    case orders = "ic_orders"
    case paint = "ic_paint"
    case paintSwatches = "ic_paint_swatches"
    case patio = "ic_patio"
    case pause = "ic_pause"
    case pdf = "ic_pdf"
    case pergola = "ic_pergola"
    case play = "ic_play"
    case playFilled = "ic_play_filled"
    case playmedia = "ic_playmedia"
    case plumbing = "ic_plumbing"
    case printer = "ic_printer"
    case profile = "ic_profile"
    case propane = "ic_propane"
    case proprofile = "ic_proprofile"
    case purchaseHistory = "ic_purchase_history"
    case pushMower = "ic_push_mower"
    case qrCode = "ic_qr_code"
    case quickAdd = "ic_quick_add"
    case recycle = "ic_recycle"
    case refresh = "ic_refresh"
    case refrigerator = "ic_refrigerator"
    case returns = "ic_returns"
    case ridingMower = "ic_riding_mower"
    case rugs = "ic_rugs"
    case ruler = "ic_ruler"
    case savings = "ic_savings"
    case saw = "ic_saw"
    case search = "ic_search"
    case secure = "ic_secure"
    case servicePro = "ic_service_pro"
    case settings = "ic_settings"
    case shareAndroid = "ic_share_android"
    case shareIos = "ic_share_ios"
    case shareWeb = "ic_share_web"
    case shed = "ic_shed"
    case shipToHome = "ic_ship_to_home"
    case show = "ic_show"
    case sortAscending = "ic_sort_ascending"
    case sortDescending = "ic_sort_descending"
    case specialSavings = "ic_special_savings"
    case starFilled = "ic_star_filled"
    case starOutline = "ic_star_outline"
    case storage = "ic_storage"
    case store = "ic_store"
    case stove = "ic_stove"
    case subscription = "ic_subscription"
    case subtract = "ic_subtract"
    case success = "ic_success"
    case successOutline = "ic_success_outline"
    case sync = "ic_sync"
    case textToConfirm = "ic_text_to_confirm"
    case thermostat = "ic_thermostat"
    case thumbsDown = "ic_thumbs_down"
    case thumbsUp = "ic_thumbs_up"
    case tile = "ic_tile"
    case trashCan = "ic_trash_can"
    case unlock = "ic_unlock"
    case upload = "ic_upload"
    case users = "ic_users"
    case van = "ic_van"
    case wallet = "ic_wallet"
    case warning = "ic_warning"
    case warningOutline = "ic_warning_outline"
    case washer = "ic_washer"
    case waterHeater = "ic_water_heater"
    case window = "ic_window"

    // MARK: - Image Access

    /// Get the SwiftUI Image for this icon
    /// Uses "Icons/" namespace prefix for xcassets organization
    public var image: Image {
        Image("Icons/\(rawValue)", bundle: .main)
    }

    /// Icon name for accessibility
    public var accessibilityLabel: String {
        rawValue.replacingOccurrences(of: "ic_", with: "")
            .replacingOccurrences(of: "_", with: " ")
            .capitalized
    }
}

// MARK: - Image Extension

extension Image {
    /// Create an image from a DSIcon
    public init(dsIcon: DSIcon) {
        self.init("Icons/\(dsIcon.rawValue)", bundle: .main)
    }
}

// MARK: - Icon Categories

extension DSIcon {
    /// Action icons (51)
    public static var actionIcons: [DSIcon] {
        [
            .threeSixtySpin, .add, .arrowBack, .arrowDown, .arrowForward, .arrowUp, .bookmarkFilled,
            .bookmarkOutline, .cancel, .cart, .checkmark, .close, .compare, .download, .duplicate,
            .edit, .email, .filters, .flag, .gridview, .heartFilled, .heartOutline, .hide,
            .listView, .menu, .more, .move, .note, .pause, .pdf, .play, .playFilled, .playmedia,
            .printer, .profile, .refresh, .search, .settings, .shareAndroid, .shareIos, .shareWeb,
            .show, .sortAscending, .sortDescending, .starFilled, .starOutline, .subtract,
            .thumbsDown, .thumbsUp, .trashCan, .upload,
        ]
    }

    /// Object icons (117)
    public static var objectIcons: [DSIcon] {
        [
            .apron, .ar, .assemble, .authorizeCard, .badge, .barcode, .bathtubs, .bell,
            .betaAddToList, .betaOrderSample, .blinds, .box, .boxTruck, .bucket, .buyAgain,
            .buyingGuide, .cabinet, .calculator, .calendar, .camera, .car, .cardCvv, .cardNumber,
            .carpetInstall, .catalog, .ceilingFan, .certificate, .chat, .clock, .cookingWares,
            .counterTop, .creditCard, .curbside, .curtain, .customOptions, .delivery,
            .deliveryexpress, .deliveryunavailable, .dishwasher, .document, .door, .downArrowleft,
            .downArrowright, .drill, .electrical, .faucets, .fence, .financialServices, .floor,
            .garage, .gas, .generator, .giftCard, .graduationCap, .grill, .hammer, .home, .howTo,
            .image, .independentLiving, .instantCheckout, .instorePickup, .key, .largeEquipment,
            .lawnGarden, .lightBulb, .lighting, .location, .locked, .locker, .mailbox, .measure,
            .medal, .mic, .mobile, .online, .orderTracking, .orders, .paint, .paintSwatches, .patio,
            .pergola, .plumbing, .propane, .proprofile, .purchaseHistory, .pushMower, .qrCode,
            .quickAdd, .recycle, .refrigerator, .returns, .ridingMower, .rugs, .ruler, .savings,
            .saw, .secure, .servicePro, .shed, .shipToHome, .specialSavings, .storage, .store,
            .stove, .subscription, .sync, .textToConfirm, .thermostat, .tile, .unlock, .users, .van,
            .wallet, .washer, .waterHeater, .window,
        ]
    }

    /// Beta icons (7)
    public static var betaIcons: [DSIcon] {
        [
            .betaAddCart, .betaLocationIcon, .betaMagicApron, .betaNumberCart, .betaPlaceholder,
            .betaQuickView, .betaSparkle,
        ]
    }

    /// Feedback icons (8)
    public static var feedbackIcons: [DSIcon] {
        [
            .danger, .dangerOutline, .info, .infoOutline, .success, .successOutline, .warning,
            .warningOutline,
        ]
    }
}
