// Generated by font-packager-ios.js
// Do not edit manually
// Font values sourced from tokens/core/typography.json

import CoreText
import SwiftUI

// MARK: - DSTypography

/// Design system typography helper for consistent font usage across components.
///
/// `DSTypography` provides pre-configured fonts that match the design system specifications,
/// ensuring consistency and avoiding issues with `.custom().weight()` combinations.
///
/// All font sizes are derived from design tokens and embedded directly for optimal performance.
///
/// ## Usage
/// ```swift
/// Text("Add to Cart")
///     .font(DSTypography.buttonLabel)
/// ```
public enum DSTypography {
    // MARK: - Font Constants

    /// Primary font family for body text
    private static let primaryFontFamily = "THD SmVar Beta"

    /// Display font family for headings and heroes
    private static let displayFontFamily = "THD LgVar Beta"

    // MARK: - Size Constants (from tokens)

    private static let sizeBodyXs: CGFloat = 12
    private static let sizeBodySm: CGFloat = 14
    private static let sizeBodyMd: CGFloat = 16
    private static let sizeBodyLg: CGFloat = 18
    private static let sizeBodyXl: CGFloat = 20
    private static let sizeH6: CGFloat = 16
    private static let sizeH5: CGFloat = 18
    private static let sizeH4: CGFloat = 20
    private static let sizeH3: CGFloat = 24
    private static let sizeH2: CGFloat = 28
    private static let sizeH1: CGFloat = 32
    private static let sizeHero5: CGFloat = 36
    private static let sizeHero4: CGFloat = 40
    private static let sizeHero3: CGFloat = 48
    private static let sizeHero2: CGFloat = 56
    private static let sizeHero1: CGFloat = 64

    // MARK: - Font Availability Check

    /// Check if a custom font is available in the system
    private static func isFontAvailable(_ fontName: String) -> Bool {
        guard let fontFamilies = CTFontManagerCopyAvailableFontFamilyNames() as? [String] else {
            return false
        }
        return fontFamilies.contains(fontName)
    }

    /// Whether we're using the system font as fallback
    private static var isUsingSystemFont: Bool {
        !isFontAvailable(primaryFontFamily)
    }

    // MARK: - Font Factory

    /// Creates a font with the specified size and weight, using custom font if available.
    /// Falls back to system font if custom font is not registered.
    ///
    /// - Parameters:
    ///   - size: The point size of the font
    ///   - weight: The weight of the font (default: .regular)
    /// - Returns: A Font configured with the appropriate family and weight
    public static func font(size: CGFloat, weight: Font.Weight = .regular) -> Font {
        if isUsingSystemFont {
            return .system(size: size, weight: weight)
        }
        return .custom(primaryFontFamily, size: size).weight(weight)
    }

    // MARK: - Button Typography

    /// Button label font - Body Sm (14px) Bold
    /// Used for all button sizes per Figma specs
    public static var buttonLabel: Font {
        font(size: sizeBodySm, weight: .bold)
    }

    /// Button label font for a specific size
    /// Note: Currently all button sizes use the same font per Figma specs
    public static func buttonLabel(size: DSButtonSize) -> Font {
        buttonLabel
    }

    // MARK: - Body Typography

    /// Body extra small font - 12px
    public static var bodyXs: Font {
        font(size: sizeBodyXs)
    }

    /// Body small font - 14px
    public static var bodySm: Font {
        font(size: sizeBodySm)
    }

    /// Body medium font - 16px
    public static var bodyMd: Font {
        font(size: sizeBodyMd)
    }

    /// Body large font - 18px
    public static var bodyLg: Font {
        font(size: sizeBodyLg)
    }

    /// Body extra large font - 20px
    public static var bodyXl: Font {
        font(size: sizeBodyXl)
    }

    // MARK: - Body Typography with Weight

    /// Body extra small bold font - 12px
    public static var bodyXsBold: Font {
        font(size: sizeBodyXs, weight: .bold)
    }

    /// Body small bold font - 14px
    public static var bodySmBold: Font {
        font(size: sizeBodySm, weight: .bold)
    }

    /// Body medium bold font - 16px
    public static var bodyMdBold: Font {
        font(size: sizeBodyMd, weight: .bold)
    }

    /// Body large bold font - 18px
    public static var bodyLgBold: Font {
        font(size: sizeBodyLg, weight: .bold)
    }

    /// Body extra large bold font - 20px
    public static var bodyXlBold: Font {
        font(size: sizeBodyXl, weight: .bold)
    }

    // MARK: - Heading Typography

    /// Heading 6 font (16px) - Semibold
    public static var h6: Font {
        font(size: sizeH6, weight: .semibold)
    }

    /// Heading 5 font (18px) - Semibold
    public static var h5: Font {
        font(size: sizeH5, weight: .semibold)
    }

    /// Heading 4 font (20px) - Semibold
    public static var h4: Font {
        font(size: sizeH4, weight: .semibold)
    }

    /// Heading 3 font (24px) - Semibold
    public static var h3: Font {
        font(size: sizeH3, weight: .semibold)
    }

    /// Heading 2 font (28px) - Semibold
    public static var h2: Font {
        font(size: sizeH2, weight: .semibold)
    }

    /// Heading 1 font (32px) - Semibold
    public static var h1: Font {
        font(size: sizeH1, weight: .semibold)
    }

    // MARK: - Heading Aliases

    /// Small heading (H5 - 18px)
    public static var headingSm: Font { h5 }

    /// Medium heading (H4 - 20px)
    public static var headingMd: Font { h4 }

    /// Large heading (H3 - 24px)
    public static var headingLg: Font { h3 }

    // MARK: - Hero Typography

    /// Hero 5 font (36px) - Bold
    public static var hero5: Font {
        font(size: sizeHero5, weight: .bold)
    }

    /// Hero 4 font (40px) - Bold
    public static var hero4: Font {
        font(size: sizeHero4, weight: .bold)
    }

    /// Hero 3 font (48px) - Bold
    public static var hero3: Font {
        font(size: sizeHero3, weight: .bold)
    }

    /// Hero 2 font (56px) - Bold
    public static var hero2: Font {
        font(size: sizeHero2, weight: .bold)
    }

    /// Hero 1 font (64px) - Bold
    public static var hero1: Font {
        font(size: sizeHero1, weight: .bold)
    }
}
