
//
// TokensCoreDark.swift
//

// Do not edit directly, this file was auto-generated.


import SwiftUI

public struct TokensCoreDark {
    public static let BodyLgBoldBaseFontFamily = "THD SmVar Beta"
    public static let BodyLgBoldBaseFontSize = 18
    public static let BodyLgBoldBaseFontWeight = "700"
    public static let BodyLgBoldBaseLetterSpacing = 0
    public static let BodyLgBoldBaseLineHeight = 150
    public static let BodyLgBoldNoneFontFamily = "THD SmVar Beta"
    public static let BodyLgBoldNoneFontSize = 18
    public static let BodyLgBoldNoneFontWeight = "700"
    public static let BodyLgBoldNoneLetterSpacing = 0
    public static let BodyLgBoldNoneLineHeight = 100
    public static let BodyLgBoldTightFontFamily = "THD SmVar Beta"
    public static let BodyLgBoldTightFontSize = 18
    public static let BodyLgBoldTightFontWeight = "700"
    public static let BodyLgBoldTightLetterSpacing = 0
    public static let BodyLgBoldTightLineHeight = 125
    public static let BodyLgRegularBaseFontFamily = "THD Sm Beta"
    public static let BodyLgRegularBaseFontSize = 18
    public static let BodyLgRegularBaseFontWeight = "400"
    public static let BodyLgRegularBaseLetterSpacing = 0
    public static let BodyLgRegularBaseLineHeight = 150
    public static let BodyLgRegularNoneFontFamily = "THD Sm Beta"
    public static let BodyLgRegularNoneFontSize = 18
    public static let BodyLgRegularNoneFontWeight = "400"
    public static let BodyLgRegularNoneLetterSpacing = 0
    public static let BodyLgRegularNoneLineHeight = 100
    public static let BodyLgRegularTightFontFamily = "THD Sm Beta"
    public static let BodyLgRegularTightFontSize = 18
    public static let BodyLgRegularTightFontWeight = "400"
    public static let BodyLgRegularTightLetterSpacing = 0
    public static let BodyLgRegularTightLineHeight = 125
    public static let BodyLgSemiboldBaseFontFamily = "SF Pro Display"
    public static let BodyLgSemiboldBaseFontSize = 18
    public static let BodyLgSemiboldBaseFontWeight = "400"
    public static let BodyLgSemiboldBaseLetterSpacing = 0
    public static let BodyLgSemiboldBaseLineHeight = 150
    public static let BodyLgSemiboldNoneFontFamily = "SF Pro Display"
    public static let BodyLgSemiboldNoneFontSize = 18
    public static let BodyLgSemiboldNoneFontWeight = "400"
    public static let BodyLgSemiboldNoneLetterSpacing = 0
    public static let BodyLgSemiboldNoneLineHeight = 100
    public static let BodyLgSemiboldTightFontFamily = "SF Pro Display"
    public static let BodyLgSemiboldTightFontSize = 18
    public static let BodyLgSemiboldTightFontWeight = "400"
    public static let BodyLgSemiboldTightLetterSpacing = 0
    public static let BodyLgSemiboldTightLineHeight = 125
    public static let BodyMdBoldBaseFontFamily = "THD SmVar Beta"
    public static let BodyMdBoldBaseFontSize = 16
    public static let BodyMdBoldBaseFontWeight = "700"
    public static let BodyMdBoldBaseLetterSpacing = 0
    public static let BodyMdBoldBaseLineHeight = 150
    public static let BodyMdBoldNoneFontFamily = "THD SmVar Beta"
    public static let BodyMdBoldNoneFontSize = 16
    public static let BodyMdBoldNoneFontWeight = "700"
    public static let BodyMdBoldNoneLetterSpacing = 0
    public static let BodyMdBoldNoneLineHeight = 100
    public static let BodyMdBoldTightFontFamily = "THD SmVar Beta"
    public static let BodyMdBoldTightFontSize = 16
    public static let BodyMdBoldTightFontWeight = "700"
    public static let BodyMdBoldTightLetterSpacing = 0
    public static let BodyMdBoldTightLineHeight = 125
    public static let BodyMdRegularBaseFontFamily = "THD Sm Beta"
    public static let BodyMdRegularBaseFontSize = 16
    public static let BodyMdRegularBaseFontWeight = "400"
    public static let BodyMdRegularBaseLetterSpacing = 0
    public static let BodyMdRegularBaseLineHeight = 150
    public static let BodyMdRegularNoneFontFamily = "THD Sm Beta"
    public static let BodyMdRegularNoneFontSize = 16
    public static let BodyMdRegularNoneFontWeight = "400"
    public static let BodyMdRegularNoneLetterSpacing = 0
    public static let BodyMdRegularNoneLineHeight = 100
    public static let BodyMdRegularTightFontFamily = "THD Sm Beta"
    public static let BodyMdRegularTightFontSize = 16
    public static let BodyMdRegularTightFontWeight = "400"
    public static let BodyMdRegularTightLetterSpacing = 0
    public static let BodyMdRegularTightLineHeight = 125
    public static let BodyMdSemiboldBaseFontFamily = "SF Pro Display"
    public static let BodyMdSemiboldBaseFontSize = 16
    public static let BodyMdSemiboldBaseFontWeight = "400"
    public static let BodyMdSemiboldBaseLetterSpacing = 0
    public static let BodyMdSemiboldBaseLineHeight = 150
    public static let BodyMdSemiboldNoneFontFamily = "SF Pro Display"
    public static let BodyMdSemiboldNoneFontSize = 16
    public static let BodyMdSemiboldNoneFontWeight = "400"
    public static let BodyMdSemiboldNoneLetterSpacing = 0
    public static let BodyMdSemiboldNoneLineHeight = 100
    public static let BodyMdSemiboldTightFontFamily = "SF Pro Display"
    public static let BodyMdSemiboldTightFontSize = 16
    public static let BodyMdSemiboldTightFontWeight = "400"
    public static let BodyMdSemiboldTightLetterSpacing = 0
    public static let BodyMdSemiboldTightLineHeight = 125
    public static let BodySmDefaultBoldBaseFontFamily = "THD SmVar Beta"
    public static let BodySmDefaultBoldBaseFontSize = 14
    public static let BodySmDefaultBoldBaseFontWeight = "700"
    public static let BodySmDefaultBoldBaseLetterSpacing = 0
    public static let BodySmDefaultBoldBaseLineHeight = 150
    public static let BodySmDefaultBoldNoneFontFamily = "THD SmVar Beta"
    public static let BodySmDefaultBoldNoneFontSize = 14
    public static let BodySmDefaultBoldNoneFontWeight = "700"
    public static let BodySmDefaultBoldNoneLetterSpacing = 0
    public static let BodySmDefaultBoldNoneLineHeight = 100
    public static let BodySmDefaultBoldTightFontFamily = "THD SmVar Beta"
    public static let BodySmDefaultBoldTightFontSize = 14
    public static let BodySmDefaultBoldTightFontWeight = "700"
    public static let BodySmDefaultBoldTightLetterSpacing = 0
    public static let BodySmDefaultBoldTightLineHeight = 125
    public static let BodySmDefaultRegularBaseFontFamily = "THD Sm Beta"
    public static let BodySmDefaultRegularBaseFontSize = 14
    public static let BodySmDefaultRegularBaseFontWeight = "400"
    public static let BodySmDefaultRegularBaseLetterSpacing = 0
    public static let BodySmDefaultRegularBaseLineHeight = 150
    public static let BodySmDefaultRegularNoneFontFamily = "THD Sm Beta"
    public static let BodySmDefaultRegularNoneFontSize = 14
    public static let BodySmDefaultRegularNoneFontWeight = "400"
    public static let BodySmDefaultRegularNoneLetterSpacing = 0
    public static let BodySmDefaultRegularNoneLineHeight = 100
    public static let BodySmDefaultRegularTightFontFamily = "THD Sm Beta"
    public static let BodySmDefaultRegularTightFontSize = 14
    public static let BodySmDefaultRegularTightFontWeight = "400"
    public static let BodySmDefaultRegularTightLetterSpacing = 0
    public static let BodySmDefaultRegularTightLineHeight = 125
    public static let BodySmDefaultSemiboldBaseFontFamily = "SF Pro Display"
    public static let BodySmDefaultSemiboldBaseFontSize = 14
    public static let BodySmDefaultSemiboldBaseFontWeight = "400"
    public static let BodySmDefaultSemiboldBaseLetterSpacing = 0
    public static let BodySmDefaultSemiboldBaseLineHeight = 150
    public static let BodySmDefaultSemiboldNoneFontFamily = "SF Pro Display"
    public static let BodySmDefaultSemiboldNoneFontSize = 14
    public static let BodySmDefaultSemiboldNoneFontWeight = "400"
    public static let BodySmDefaultSemiboldNoneLetterSpacing = 0
    public static let BodySmDefaultSemiboldNoneLineHeight = 100
    public static let BodySmDefaultSemiboldTightFontFamily = "SF Pro Display"
    public static let BodySmDefaultSemiboldTightFontSize = 14
    public static let BodySmDefaultSemiboldTightFontWeight = "400"
    public static let BodySmDefaultSemiboldTightLetterSpacing = 0
    public static let BodySmDefaultSemiboldTightLineHeight = 125
    public static let BodyXlBoldBaseFontFamily = "THD SmVar Beta"
    public static let BodyXlBoldBaseFontSize = 20
    public static let BodyXlBoldBaseFontWeight = "700"
    public static let BodyXlBoldBaseLetterSpacing = 0
    public static let BodyXlBoldBaseLineHeight = 150
    public static let BodyXlBoldNoneFontFamily = "THD SmVar Beta"
    public static let BodyXlBoldNoneFontSize = 20
    public static let BodyXlBoldNoneFontWeight = "700"
    public static let BodyXlBoldNoneLetterSpacing = 0
    public static let BodyXlBoldNoneLineHeight = 100
    public static let BodyXlBoldTightFontFamily = "THD SmVar Beta"
    public static let BodyXlBoldTightFontSize = 20
    public static let BodyXlBoldTightFontWeight = "700"
    public static let BodyXlBoldTightLetterSpacing = 0
    public static let BodyXlBoldTightLineHeight = 125
    public static let BodyXlRegularBaseFontFamily = "THD SmVar Beta"
    public static let BodyXlRegularBaseFontSize = 20
    public static let BodyXlRegularBaseFontWeight = "400"
    public static let BodyXlRegularBaseLetterSpacing = 0
    public static let BodyXlRegularBaseLineHeight = 150
    public static let BodyXlRegularNoneFontFamily = "THD SmVar Beta"
    public static let BodyXlRegularNoneFontSize = 20
    public static let BodyXlRegularNoneFontWeight = "400"
    public static let BodyXlRegularNoneLetterSpacing = 0
    public static let BodyXlRegularNoneLineHeight = 100
    public static let BodyXlRegularTightFontFamily = "THD SmVar Beta"
    public static let BodyXlRegularTightFontSize = 20
    public static let BodyXlRegularTightFontWeight = "400"
    public static let BodyXlRegularTightLetterSpacing = 0
    public static let BodyXlRegularTightLineHeight = 125
    public static let BodyXlSemiboldBaseFontFamily = "SF Pro Display"
    public static let BodyXlSemiboldBaseFontSize = 20
    public static let BodyXlSemiboldBaseFontWeight = "400"
    public static let BodyXlSemiboldBaseLetterSpacing = 0
    public static let BodyXlSemiboldBaseLineHeight = 150
    public static let BodyXlSemiboldNoneFontFamily = "SF Pro Display"
    public static let BodyXlSemiboldNoneFontSize = 20
    public static let BodyXlSemiboldNoneFontWeight = "400"
    public static let BodyXlSemiboldNoneLetterSpacing = 0
    public static let BodyXlSemiboldNoneLineHeight = 100
    public static let BodyXlSemiboldTightFontFamily = "SF Pro Display"
    public static let BodyXlSemiboldTightFontSize = 20
    public static let BodyXlSemiboldTightFontWeight = "400"
    public static let BodyXlSemiboldTightLetterSpacing = 0
    public static let BodyXlSemiboldTightLineHeight = 125
    public static let BodyXsBoldBaseFontFamily = "THD SmVar Beta"
    public static let BodyXsBoldBaseFontSize = 12
    public static let BodyXsBoldBaseFontWeight = "700"
    public static let BodyXsBoldBaseLetterSpacing = 0
    public static let BodyXsBoldBaseLineHeight = 150
    public static let BodyXsBoldNoneFontFamily = "THD SmVar Beta"
    public static let BodyXsBoldNoneFontSize = 12
    public static let BodyXsBoldNoneFontWeight = "700"
    public static let BodyXsBoldNoneLetterSpacing = 0
    public static let BodyXsBoldNoneLineHeight = 100
    public static let BodyXsBoldTightFontFamily = "THD SmVar Beta"
    public static let BodyXsBoldTightFontSize = 12
    public static let BodyXsBoldTightFontWeight = "700"
    public static let BodyXsBoldTightLetterSpacing = 0
    public static let BodyXsBoldTightLineHeight = 125
    public static let BodyXsRegularBaseFontFamily = "THD Sm Beta"
    public static let BodyXsRegularBaseFontSize = 12
    public static let BodyXsRegularBaseFontWeight = "400"
    public static let BodyXsRegularBaseLetterSpacing = 0
    public static let BodyXsRegularBaseLineHeight = 150
    public static let BodyXsRegularNoneFontFamily = "THD Sm Beta"
    public static let BodyXsRegularNoneFontSize = 12
    public static let BodyXsRegularNoneFontWeight = "400"
    public static let BodyXsRegularNoneLetterSpacing = 0
    public static let BodyXsRegularNoneLineHeight = 100
    public static let BodyXsRegularTightFontFamily = "THD Sm Beta"
    public static let BodyXsRegularTightFontSize = 12
    public static let BodyXsRegularTightFontWeight = "400"
    public static let BodyXsRegularTightLetterSpacing = 0
    public static let BodyXsRegularTightLineHeight = 125
    public static let BodyXsSemiboldBaseFontFamily = "SF Pro Display"
    public static let BodyXsSemiboldBaseFontSize = 12
    public static let BodyXsSemiboldBaseFontWeight = "400"
    public static let BodyXsSemiboldBaseLetterSpacing = 0
    public static let BodyXsSemiboldBaseLineHeight = 150
    public static let BodyXsSemiboldNoneFontFamily = "SF Pro Display"
    public static let BodyXsSemiboldNoneFontSize = 12
    public static let BodyXsSemiboldNoneFontWeight = "400"
    public static let BodyXsSemiboldNoneLetterSpacing = 0
    public static let BodyXsSemiboldNoneLineHeight = 100
    public static let BodyXsSemiboldTightFontFamily = "SF Pro Display"
    public static let BodyXsSemiboldTightFontSize = 12
    public static let BodyXsSemiboldTightFontWeight = "400"
    public static let BodyXsSemiboldTightLetterSpacing = 0
    public static let BodyXsSemiboldTightLineHeight = 125
    public static let ElevationAbove1 = DSShadow(x: 0, y: -1, blur: 4, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationAbove2 = DSShadow(x: 0, y: -3, blur: 8, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationAbove3 = DSShadow(x: 0, y: -4, blur: 12, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationAbove4 = DSShadow(x: 0, y: -8, blur: 16, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationAbove5 = DSShadow(x: 0, y: -16, blur: 24, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBelow1 = DSShadow(x: 1, y: 1, blur: 4, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBelow2 = DSShadow(x: 0, y: 3, blur: 8, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBelow3 = DSShadow(x: 0, y: 4, blur: 12, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBelow4 = DSShadow(x: 0, y: 8, blur: 16, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBelow5 = DSShadow(x: 0, y: 16, blur: 24, spread: 0, color: Color(red: 0, green: 0, blue: 0, opacity: 0.122))
    public static let ElevationBlurRadiusBlur1 = CGFloat(4)
    public static let ElevationBlurRadiusBlur2 = CGFloat(8)
    public static let ElevationBlurRadiusBlur3 = CGFloat(12)
    public static let ElevationBlurRadiusBlur4 = CGFloat(16)
    public static let ElevationBlurRadiusBlur5 = CGFloat(24)
    public static let ElevationHigh = Color(red: 0, green: 0, blue: 0, opacity: 0.18)
    public static let ElevationHighest = Color(red: 0, green: 0, blue: 0, opacity: 0.239)
    public static let ElevationLow = Color(red: 0, green: 0, blue: 0, opacity: 0.102)
    public static let ElevationLowest = Color(red: 0, green: 0, blue: 0, opacity: 0.051)
    public static let ElevationMed = Color(red: 0, green: 0, blue: 0, opacity: 0.122)
    public static let ElevationPositionX1 = CGFloat(1)
    public static let ElevationPositionX2 = CGFloat(3)
    public static let ElevationPositionX3 = CGFloat(4)
    public static let ElevationPositionX4 = CGFloat(8)
    public static let ElevationPositionX5 = CGFloat(16)
    public static let ElevationPositionY1 = CGFloat(1)
    public static let ElevationPositionY2 = CGFloat(3)
    public static let ElevationPositionY3 = CGFloat(4)
    public static let ElevationPositionY4 = CGFloat(8)
    public static let ElevationPositionY5 = CGFloat(16)
    public static let FontFamilyDisplay = "THD LgVar Beta"
    public static let FontFamilyInformational = "THD SmVar Beta"
    public static let FontLetterSpacingBase = CGFloat(0)
    public static let FontLetterSpacingNlarge = CGFloat(-0.05)
    public static let FontLetterSpacingNsmall = CGFloat(-0.02)
    public static let FontLetterSpacingPlarge = CGFloat(0.05)
    public static let FontLetterSpacingPsmall = CGFloat(0.02)
    public static let FontLineHeightBase = CGFloat(1.5)
    public static let FontLineHeightNone = CGFloat(1)
    public static let FontLineHeightTight = CGFloat(1.25)
    public static let FontSizeBodyLg = CGFloat(18)
    public static let FontSizeBodyMd = CGFloat(16)
    public static let FontSizeBodySm = CGFloat(14)
    public static let FontSizeBodyXl = CGFloat(20)
    public static let FontSizeBodyXs = CGFloat(12)
    public static let FontSizeCaption = CGFloat(11)
    public static let FontSizeH1 = CGFloat(32)
    public static let FontSizeH2 = CGFloat(28)
    public static let FontSizeH3 = CGFloat(24)
    public static let FontSizeH4 = CGFloat(20)
    public static let FontSizeH5 = CGFloat(18)
    public static let FontSizeH6 = CGFloat(16)
    public static let FontSizeHero1 = CGFloat(64)
    public static let FontSizeHero2 = CGFloat(56)
    public static let FontSizeHero3 = CGFloat(48)
    public static let FontSizeHero4 = CGFloat(40)
    public static let FontSizeHero5 = CGFloat(36)
    public static let FontWeightBodyBold = "Bold"
    public static let FontWeightBodyLight = "Light"
    public static let FontWeightBodyMedium = "Medium"
    public static let FontWeightBodyRegular = "Regular"
    public static let FontWeightBodySemibold = "SemiBold"
    public static let FontWeightCondensedBold = CGFloat(48)
    public static let FontWeightCondensedRegular = CGFloat(56)
    public static let FontWeightCondensedSemibold = CGFloat(37)
    public static let FontWeightHeadingBold = "Bold"
    public static let FontWeightHeadingExtrabold = "ExtraBold"
    public static let FontWeightHeadingSemibold = "SemiBold"
    public static let GradientBrandPrimary = LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 0.984, green: 0.635, blue: 0.408, opacity: 1), location: 0), .init(color: Color(red: 0.914, green: 0.361, blue: 0.008, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0, y: 0.5), endPoint: UnitPoint(x: 1, y: 0.5)) /** Primary brand gradient (light orange to dark orange, left to right) */
    public static let GradientBrandSecondary = LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 0.976, green: 0.388, blue: 0.008, opacity: 1), location: 0), .init(color: Color(red: 0.792, green: 0.314, blue: 0.008, opacity: 1), location: 0.5), .init(color: Color(red: 0.584, green: 0.231, blue: 0.004, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0.1464, y: 0.1464), endPoint: UnitPoint(x: 0.8536, y: 0.8536)) /** Secondary brand gradient with 3 stops */
    public static let GradientSurfaceSubtle = LinearGradient(gradient: Gradient(stops: [.init(color: Color(red: 0.898, green: 0.882, blue: 0.871, opacity: 1), location: 0), .init(color: Color(red: 0.729, green: 0.718, blue: 0.706, opacity: 1), location: 1)]), startPoint: UnitPoint(x: 0.5, y: 0), endPoint: UnitPoint(x: 0.5, y: 1)) /** Subtle surface gradient for backgrounds */
    public static let HeadingH1ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH1ExtraboldBaseFontSize = 32
    public static let HeadingH1ExtraboldBaseFontWeight = "400"
    public static let HeadingH1ExtraboldBaseLetterSpacing = 0
    public static let HeadingH1ExtraboldBaseLineHeight = 150
    public static let HeadingH1ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH1ExtraboldNoneFontSize = 32
    public static let HeadingH1ExtraboldNoneFontWeight = "400"
    public static let HeadingH1ExtraboldNoneLetterSpacing = 0
    public static let HeadingH1ExtraboldNoneLineHeight = 100
    public static let HeadingH1ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH1ExtraboldTightFontSize = 32
    public static let HeadingH1ExtraboldTightFontWeight = "400"
    public static let HeadingH1ExtraboldTightLetterSpacing = 0
    public static let HeadingH1ExtraboldTightLineHeight = 125
    public static let HeadingH1SemiboldBaseFontFamily = "THD Sm Beta"
    public static let HeadingH1SemiboldBaseFontSize = 32
    public static let HeadingH1SemiboldBaseFontWeight = "500"
    public static let HeadingH1SemiboldBaseLetterSpacing = 0
    public static let HeadingH1SemiboldBaseLineHeight = 150
    public static let HeadingH1SemiboldNoneFontFamily = "THD Sm Beta"
    public static let HeadingH1SemiboldNoneFontSize = 32
    public static let HeadingH1SemiboldNoneFontWeight = "400"
    public static let HeadingH1SemiboldNoneLetterSpacing = 0
    public static let HeadingH1SemiboldNoneLineHeight = 100
    public static let HeadingH1SemiboldTightFontFamily = "THD Sm Beta"
    public static let HeadingH1SemiboldTightFontSize = 32
    public static let HeadingH1SemiboldTightFontWeight = "500"
    public static let HeadingH1SemiboldTightLetterSpacing = 0
    public static let HeadingH1SemiboldTightLineHeight = 125
    public static let HeadingH2ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH2ExtraboldBaseFontSize = 28
    public static let HeadingH2ExtraboldBaseFontWeight = "400"
    public static let HeadingH2ExtraboldBaseLetterSpacing = 0
    public static let HeadingH2ExtraboldBaseLineHeight = 150
    public static let HeadingH2ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH2ExtraboldNoneFontSize = 28
    public static let HeadingH2ExtraboldNoneFontWeight = "400"
    public static let HeadingH2ExtraboldNoneLetterSpacing = 0
    public static let HeadingH2ExtraboldNoneLineHeight = 100
    public static let HeadingH2ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH2ExtraboldTightFontSize = 28
    public static let HeadingH2ExtraboldTightFontWeight = "400"
    public static let HeadingH2ExtraboldTightLetterSpacing = 0
    public static let HeadingH2ExtraboldTightLineHeight = 125
    public static let HeadingH2SemiboldBaseFontFamily = "SF Pro Display"
    public static let HeadingH2SemiboldBaseFontSize = 28
    public static let HeadingH2SemiboldBaseFontWeight = "400"
    public static let HeadingH2SemiboldBaseLetterSpacing = 0
    public static let HeadingH2SemiboldBaseLineHeight = 150
    public static let HeadingH2SemiboldNoneFontFamily = "SF Pro Display"
    public static let HeadingH2SemiboldNoneFontSize = 28
    public static let HeadingH2SemiboldNoneFontWeight = "400"
    public static let HeadingH2SemiboldNoneLetterSpacing = 0
    public static let HeadingH2SemiboldNoneLineHeight = 100
    public static let HeadingH2SemiboldTightFontFamily = "SF Pro Display"
    public static let HeadingH2SemiboldTightFontSize = 28
    public static let HeadingH2SemiboldTightFontWeight = "400"
    public static let HeadingH2SemiboldTightLetterSpacing = 0
    public static let HeadingH2SemiboldTightLineHeight = 125
    public static let HeadingH3ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH3ExtraboldBaseFontSize = 24
    public static let HeadingH3ExtraboldBaseFontWeight = "400"
    public static let HeadingH3ExtraboldBaseLetterSpacing = 0
    public static let HeadingH3ExtraboldBaseLineHeight = 150
    public static let HeadingH3ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH3ExtraboldNoneFontSize = 24
    public static let HeadingH3ExtraboldNoneFontWeight = "400"
    public static let HeadingH3ExtraboldNoneLetterSpacing = 0
    public static let HeadingH3ExtraboldNoneLineHeight = 100
    public static let HeadingH3ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH3ExtraboldTightFontSize = 24
    public static let HeadingH3ExtraboldTightFontWeight = "400"
    public static let HeadingH3ExtraboldTightLetterSpacing = 0
    public static let HeadingH3ExtraboldTightLineHeight = 125
    public static let HeadingH3SemiboldBaseFontFamily = "SF Pro Display"
    public static let HeadingH3SemiboldBaseFontSize = 24
    public static let HeadingH3SemiboldBaseFontWeight = "400"
    public static let HeadingH3SemiboldBaseLetterSpacing = 0
    public static let HeadingH3SemiboldBaseLineHeight = 150
    public static let HeadingH3SemiboldNoneFontFamily = "SF Pro Display"
    public static let HeadingH3SemiboldNoneFontSize = 24
    public static let HeadingH3SemiboldNoneFontWeight = "400"
    public static let HeadingH3SemiboldNoneLetterSpacing = 0
    public static let HeadingH3SemiboldNoneLineHeight = 100
    public static let HeadingH3SemiboldTightFontFamily = "SF Pro Display"
    public static let HeadingH3SemiboldTightFontSize = 24
    public static let HeadingH3SemiboldTightFontWeight = "400"
    public static let HeadingH3SemiboldTightLetterSpacing = 0
    public static let HeadingH3SemiboldTightLineHeight = 125
    public static let HeadingH4ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH4ExtraboldBaseFontSize = 20
    public static let HeadingH4ExtraboldBaseFontWeight = "400"
    public static let HeadingH4ExtraboldBaseLetterSpacing = 0
    public static let HeadingH4ExtraboldBaseLineHeight = 150
    public static let HeadingH4ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH4ExtraboldNoneFontSize = 20
    public static let HeadingH4ExtraboldNoneFontWeight = "400"
    public static let HeadingH4ExtraboldNoneLetterSpacing = 0
    public static let HeadingH4ExtraboldNoneLineHeight = 100
    public static let HeadingH4ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH4ExtraboldTightFontSize = 20
    public static let HeadingH4ExtraboldTightFontWeight = "400"
    public static let HeadingH4ExtraboldTightLetterSpacing = 0
    public static let HeadingH4ExtraboldTightLineHeight = 125
    public static let HeadingH4SemiboldBaseFontFamily = "THD Sm Beta"
    public static let HeadingH4SemiboldBaseFontSize = 20
    public static let HeadingH4SemiboldBaseFontWeight = "500"
    public static let HeadingH4SemiboldBaseLetterSpacing = 0
    public static let HeadingH4SemiboldBaseLineHeight = 150
    public static let HeadingH4SemiboldNoneFontFamily = "SF Pro Display"
    public static let HeadingH4SemiboldNoneFontSize = 20
    public static let HeadingH4SemiboldNoneFontWeight = "400"
    public static let HeadingH4SemiboldNoneLetterSpacing = 0
    public static let HeadingH4SemiboldNoneLineHeight = 100
    public static let HeadingH4SemiboldTightFontFamily = "THD Sm Beta"
    public static let HeadingH4SemiboldTightFontSize = 20
    public static let HeadingH4SemiboldTightFontWeight = "400"
    public static let HeadingH4SemiboldTightLetterSpacing = 0
    public static let HeadingH4SemiboldTightLineHeight = 125
    public static let HeadingH5ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH5ExtraboldBaseFontSize = 18
    public static let HeadingH5ExtraboldBaseFontWeight = "400"
    public static let HeadingH5ExtraboldBaseLetterSpacing = 0
    public static let HeadingH5ExtraboldBaseLineHeight = 150
    public static let HeadingH5ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH5ExtraboldNoneFontSize = 18
    public static let HeadingH5ExtraboldNoneFontWeight = "400"
    public static let HeadingH5ExtraboldNoneLetterSpacing = 0
    public static let HeadingH5ExtraboldNoneLineHeight = 100
    public static let HeadingH5ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH5ExtraboldTightFontSize = 18
    public static let HeadingH5ExtraboldTightFontWeight = "400"
    public static let HeadingH5ExtraboldTightLetterSpacing = 0
    public static let HeadingH5ExtraboldTightLineHeight = 125
    public static let HeadingH5SemiboldBaseFontFamily = "THD Sm Beta"
    public static let HeadingH5SemiboldBaseFontSize = 18
    public static let HeadingH5SemiboldBaseFontWeight = "400"
    public static let HeadingH5SemiboldBaseLetterSpacing = 0
    public static let HeadingH5SemiboldBaseLineHeight = 150
    public static let HeadingH5SemiboldNoneFontFamily = "THD Sm Beta"
    public static let HeadingH5SemiboldNoneFontSize = 18
    public static let HeadingH5SemiboldNoneFontWeight = "400"
    public static let HeadingH5SemiboldNoneLetterSpacing = 0
    public static let HeadingH5SemiboldNoneLineHeight = 100
    public static let HeadingH5SemiboldTightFontFamily = "THD Sm Beta"
    public static let HeadingH5SemiboldTightFontSize = 18
    public static let HeadingH5SemiboldTightFontWeight = "400"
    public static let HeadingH5SemiboldTightLetterSpacing = 0
    public static let HeadingH5SemiboldTightLineHeight = 125
    public static let HeadingH6ExtraboldBaseFontFamily = "THD SmVar Beta"
    public static let HeadingH6ExtraboldBaseFontSize = 16
    public static let HeadingH6ExtraboldBaseFontWeight = "400"
    public static let HeadingH6ExtraboldBaseLetterSpacing = 0
    public static let HeadingH6ExtraboldBaseLineHeight = 150
    public static let HeadingH6ExtraboldNoneFontFamily = "THD SmVar Beta"
    public static let HeadingH6ExtraboldNoneFontSize = 16
    public static let HeadingH6ExtraboldNoneFontWeight = "400"
    public static let HeadingH6ExtraboldNoneLetterSpacing = 0
    public static let HeadingH6ExtraboldNoneLineHeight = 100
    public static let HeadingH6ExtraboldTightFontFamily = "THD SmVar Beta"
    public static let HeadingH6ExtraboldTightFontSize = 16
    public static let HeadingH6ExtraboldTightFontWeight = "400"
    public static let HeadingH6ExtraboldTightLetterSpacing = 0
    public static let HeadingH6ExtraboldTightLineHeight = 125
    public static let HeadingH6SemiboldBaseFontFamily = "THD Sm Beta"
    public static let HeadingH6SemiboldBaseFontSize = 16
    public static let HeadingH6SemiboldBaseFontWeight = "500"
    public static let HeadingH6SemiboldBaseLetterSpacing = 0
    public static let HeadingH6SemiboldBaseLineHeight = 150
    public static let HeadingH6SemiboldNoneFontFamily = "THD Sm Beta"
    public static let HeadingH6SemiboldNoneFontSize = 16
    public static let HeadingH6SemiboldNoneFontWeight = "500"
    public static let HeadingH6SemiboldNoneLetterSpacing = 0
    public static let HeadingH6SemiboldNoneLineHeight = 100
    public static let HeadingH6SemiboldTightFontFamily = "THD Sm Beta"
    public static let HeadingH6SemiboldTightFontSize = 16
    public static let HeadingH6SemiboldTightFontWeight = "500"
    public static let HeadingH6SemiboldTightLetterSpacing = 0
    public static let HeadingH6SemiboldTightLineHeight = 125
    public static let Radius = CGFloat(0)
    public static let Radius0 = CGFloat(0)
    public static let Radius1 = CGFloat(1)
    public static let Radius10 = CGFloat(24)
    public static let Radius11 = CGFloat(28)
    public static let Radius12 = CGFloat(32)
    public static let Radius13 = CGFloat(36)
    public static let Radius14 = CGFloat(40)
    public static let Radius15 = CGFloat(44)
    public static let Radius16 = CGFloat(48)
    public static let Radius17 = CGFloat(52)
    public static let Radius18 = CGFloat(56)
    public static let Radius19 = CGFloat(60)
    public static let Radius2 = CGFloat(2)
    public static let Radius20 = CGFloat(64)
    public static let Radius3 = CGFloat(3)
    public static let Radius4 = CGFloat(4)
    public static let Radius5 = CGFloat(6)
    public static let Radius6 = CGFloat(8)
    public static let Radius7 = CGFloat(12)
    public static let Radius8 = CGFloat(16)
    public static let Radius9 = CGFloat(20)
    public static let Radius999 = CGFloat(9999)
    public static let Spacing0 = CGFloat(0) /** 0 */
    public static let Spacing1 = CGFloat(4) /** 4 */
    public static let Spacing10 = CGFloat(40) /** 40 */
    public static let Spacing11 = CGFloat(44) /** 44 */
    public static let Spacing12 = CGFloat(48) /** 48 */
    public static let Spacing13 = CGFloat(52) /** 52 */
    public static let Spacing14 = CGFloat(56) /** 56 */
    public static let Spacing15 = CGFloat(60) /** 60 */
    public static let Spacing16 = CGFloat(64) /** 64 */
    public static let Spacing17 = CGFloat(68) /** 68 */
    public static let Spacing18 = CGFloat(72) /** 72 */
    public static let Spacing19 = CGFloat(76) /** 76 */
    public static let Spacing1px = CGFloat(1) /** 1 */
    public static let Spacing2 = CGFloat(8) /** 8 */
    public static let Spacing20 = CGFloat(80) /** 80 */
    public static let Spacing21 = CGFloat(84) /** 84 */
    public static let Spacing22 = CGFloat(88) /** 88 */
    public static let Spacing23 = CGFloat(92) /** 92 */
    public static let Spacing24 = CGFloat(96) /** 96 */
    public static let Spacing25 = CGFloat(100) /** 100 */
    public static let Spacing26 = CGFloat(104) /** 104 */
    public static let Spacing27 = CGFloat(108) /** 108 */
    public static let Spacing28 = CGFloat(112) /** 112 */
    public static let Spacing29 = CGFloat(116) /** 116 */
    public static let Spacing2Tba = CGFloat(6) /** 6 */
    public static let Spacing2px = CGFloat(2) /** 2 */
    public static let Spacing3 = CGFloat(12) /** 12 */
    public static let Spacing30 = CGFloat(120) /** 120 */
    public static let Spacing31 = CGFloat(124) /** 124 */
    public static let Spacing32 = CGFloat(128) /** 128 */
    public static let Spacing33 = CGFloat(132) /** 132 */
    public static let Spacing34 = CGFloat(136) /** 136 */
    public static let Spacing35 = CGFloat(140) /** 140 */
    public static let Spacing36 = CGFloat(144)
    public static let Spacing4 = CGFloat(16) /** 16 */
    public static let Spacing5 = CGFloat(20) /** 20 */
    public static let Spacing6 = CGFloat(24) /** 24 */
    public static let Spacing6px = CGFloat(6)
    public static let Spacing7 = CGFloat(28) /** 28 */
    public static let Spacing8 = CGFloat(32) /** 32 */
    public static let Spacing9 = CGFloat(36) /** 36 */
}